"""version_5

Revision ID: 15994dd50b7d
Revises: 1b2dcf54fd0f
Create Date: 2020-02-18 16:05:25.959996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15994dd50b7d'
down_revision = '1b2dcf54fd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
