"""version_4

Revision ID: 1b2dcf54fd0f
Revises: 53ee140fb14c
Create Date: 2020-02-18 16:04:54.739148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2dcf54fd0f'
down_revision = '53ee140fb14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
