"""version_3

Revision ID: 53ee140fb14c
Revises: 51c9d9667ad4
Create Date: 2020-02-18 16:03:48.631975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ee140fb14c'
down_revision = '51c9d9667ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
